name: nps_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.1
  pointycastle: ^3.6.2
  http: ^0.13.5
  sizer: ^2.0.15
  flutter_svg: ^1.1.5
  flutter_phoenix: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true
  assets:
    - assets/
    - assets/public_key.pem
    - assets/Logo/PGIM_Logo.svg
    - assets/Logo/whiteLogo.png
  
  fonts:
    - family: Arial Narrow
      fonts:
        - asset: assets/fonts/Arial Narrow/ARIALN.ttf
        - asset: assets/fonts/Arial Narrow/ARIALNI.ttf
          style: italic
        - asset: assets/fonts/Arial Narrow/ARIALNB.ttf
          weight: 700
    - family: Times New Roman
      fonts:
        - asset: assets/fonts/Times New Roman/times new roman.ttf
        - asset: assets/fonts/Times New Roman/times new roman bold.ttf
          weight: 700
        - asset: assets/fonts/Times New Roman/times new roman italic.ttf
          style: italic
 
